// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Author: Noby Grand (https://sketchfab.com/NobyGrand)
// License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
// Source: https://sketchfab.com/3d-models/ghost-w-tophat-6b1217e3462440519a2d0e3e75bf16d3
// Title: Ghost w/ Tophat
// */

// import { useGLTF } from '@react-three/drei'

// export default function CharacterModel(props) {
//     const { nodes, materials } = useGLTF('./ghost_w_tophat.glb')
//     return (
//         <group {...props} dispose={null}>
//             <group scale={0.0034} position={[0, -0.55, 0]}>
//                 <group position={[0, 155.777, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
//                     <mesh castShadow receiveShadow geometry={nodes.Eyes_Eyes_0.geometry} material={materials.Eyes} />
//                     <mesh castShadow receiveShadow geometry={nodes.Eyes_Ghost_White_0.geometry} material={materials.Ghost_White} />
//                 </group>
//                 <mesh
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.Body_Ghost_White_0.geometry}
//                     material={materials.Ghost_White}
//                     position={[0, 155.777, 0]}
//                     rotation={[-Math.PI / 2, 0, 0]}
//                     scale={100}
//                 />
//                 <mesh
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.Hat_Hat_Black_0.geometry}
//                     material={materials.Hat_Black}
//                     position={[0, 299.13, 0]}
//                     rotation={[-Math.PI / 2, 0, 0]}
//                     scale={100}
//                 />
//                 <mesh
//                     castShadow
//                     receiveShadow
//                     geometry={nodes.Rim_Rim_Red_0.geometry}
//                     material={materials.Rim_Red}
//                     position={[0, 235.411, 0]}
//                     rotation={[-Math.PI / 2, 0, 0]}
//                     scale={100}
//                 />
//             </group>
//         </group>
//     )
// }

// useGLTF.preload('./ghost_w_tophat.glb')

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Model(props) {
    const { nodes, materials } = useGLTF("/player.glb");

    return (
        <group {...props} dispose={null} position={[0, 0.2, 0]}>
            <primitive object={nodes.Hips} />
            <skinnedMesh
                name="EyeLeft"
                geometry={nodes.EyeLeft.geometry}
                material={materials.Wolf3D_Eye}
                skeleton={nodes.EyeLeft.skeleton}
                morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
                morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
            />
            <skinnedMesh
                name="EyeRight"
                geometry={nodes.EyeRight.geometry}
                material={materials.Wolf3D_Eye}
                skeleton={nodes.EyeRight.skeleton}
                morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
                morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
            />
            <skinnedMesh
                name="Wolf3D_Head"
                geometry={nodes.Wolf3D_Head.geometry}
                material={materials.Wolf3D_Skin}
                skeleton={nodes.Wolf3D_Head.skeleton}
                morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
                morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
            />
            <skinnedMesh
                name="Wolf3D_Teeth"
                geometry={nodes.Wolf3D_Teeth.geometry}
                material={materials.Wolf3D_Teeth}
                skeleton={nodes.Wolf3D_Teeth.skeleton}
                morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
                morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
            />
            <skinnedMesh
                geometry={nodes.Wolf3D_Hair.geometry}
                material={materials.Wolf3D_Hair}
                skeleton={nodes.Wolf3D_Hair.skeleton}
            />
            <skinnedMesh
                geometry={nodes.Wolf3D_Glasses.geometry}
                material={materials.Wolf3D_Glasses}
                skeleton={nodes.Wolf3D_Glasses.skeleton}
            />
            <skinnedMesh
                name="Wolf3D_Outfit_Top"
                geometry={nodes.Wolf3D_Outfit_Top.geometry}
                material={materials.Wolf3D_Outfit_Top}
                skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
                morphTargetDictionary={nodes.Wolf3D_Outfit_Top.morphTargetDictionary}
                morphTargetInfluences={nodes.Wolf3D_Outfit_Top.morphTargetInfluences}
            />
            <skinnedMesh
                name="Wolf3D_Outfit_Bottom"
                geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
                material={materials.Wolf3D_Outfit_Bottom}
                skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
                morphTargetDictionary={nodes.Wolf3D_Outfit_Bottom.morphTargetDictionary}
                morphTargetInfluences={nodes.Wolf3D_Outfit_Bottom.morphTargetInfluences}
            />
            <skinnedMesh
                name="Wolf3D_Outfit_Footwear"
                geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
                material={materials.Wolf3D_Outfit_Footwear}
                skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
                morphTargetDictionary={
                    nodes.Wolf3D_Outfit_Footwear.morphTargetDictionary
                }
                morphTargetInfluences={
                    nodes.Wolf3D_Outfit_Footwear.morphTargetInfluences
                }
            />
            <skinnedMesh
                name="Wolf3D_Body"
                geometry={nodes.Wolf3D_Body.geometry}
                material={materials.Wolf3D_Body}
                skeleton={nodes.Wolf3D_Body.skeleton}
                morphTargetDictionary={nodes.Wolf3D_Body.morphTargetDictionary}
                morphTargetInfluences={nodes.Wolf3D_Body.morphTargetInfluences}
            />
        </group>
    );
}

useGLTF.preload("/player.glb");
