/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: rukitu (https://sketchfab.com/rukitu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pop-cat-2d1c8b8514684b0a8d1b8203caa01a95
Title: POP CAT
*/

//disable eslint and typescript for this file
/* eslint-disable */
// @ts-nocheck

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { editable as e } from '@theatre/r3f'

export default function PopCat(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF("/pop_cat.glb");
    const { actions } = useAnimations(animations, group);

    useEffect(() => {
        actions["Animation"].play();
    }, [actions]);

    return (
        <e.group theatreKey="PopCat" ref={group} {...props} scale={[0.05, 0.05, 0.05]} dispose={null}>
            <group name="Sketchfab_Scene">
                <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
                    <group name="root">
                        <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
                            <group
                                name="tail_1"
                                position={[0.484, 7.965, -0.993]}
                                scale={1.211}
                            >
                                <mesh
                                    name="Object_4"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Object_4.geometry}
                                    material={materials["Material.004"]}
                                />
                            </group>
                            <group
                                name="cat_6"
                                position={[0.484, 7.723, -0.993]}
                                scale={1.211}
                            >
                                <mesh
                                    name="mesh_1"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.mesh_1.geometry}
                                    material={materials["Material.004"]}
                                    morphTargetDictionary={nodes.mesh_1.morphTargetDictionary}
                                    morphTargetInfluences={nodes.mesh_1.morphTargetInfluences}
                                />
                            </group>
                            <group
                                name="cat001_7"
                                position={[9.642, 7.723, -0.993]}
                                scale={1.211}
                            >
                                <mesh
                                    name="mesh_2"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.mesh_2.geometry}
                                    material={materials["Material.004"]}
                                    morphTargetDictionary={nodes.mesh_2.morphTargetDictionary}
                                    morphTargetInfluences={nodes.mesh_2.morphTargetInfluences}
                                />
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </e.group>
    );
}

useGLTF.preload("/pop_cat.glb");
