/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: geniusrahman155 (https://sketchfab.com/geniusrahman155)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-multi-storied-building-fc8e064896af402587697d0523038938
Title: low poly multi storied building
*/
//disable eslint and typescript for this file
/* eslint-disable */
// @ts-nocheck

import React, { useRef, useMemo, useContext, createContext } from 'react'
import { useGLTF, Merged } from '@react-three/drei'
import { editable as e } from '@theatre/r3f'

const context = createContext()
export function Instances({ children, ...props }) {
    const { nodes } = useGLTF('/low_poly_multi_storied_building.glb')
    const instances = useMemo(
        () => ({
            BoxMaterial: nodes['Box001_Material_#25_0'],
        }),
        [nodes]
    )
    return (
        <Merged meshes={instances} {...props}>
            {(instances) => <context.Provider value={instances} children={children} />}
        </Merged>
    )
}

export function Building_2(props) {
    const instances = useContext(context)
    return (
        <group theatreKey='building2' {...props} dispose={null}>
            <instances.BoxMaterial position={[0.391, 0, 4.173]} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
    )
}

useGLTF.preload('/low_poly_multi_storied_building.glb')
