/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: geniusrahman155 (https://sketchfab.com/geniusrahman155)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/building-3-f73bbeed660a4596997ad9a262be081b
Title: building 3
*/

//disable eslint and typescript for this file
/* eslint-disable */
// @ts-nocheck

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { editable as e } from '@theatre/r3f'

export function Building_1(props) {
    const { nodes, materials } = useGLTF('/building_3.glb')
    return (
        <e.group theatreKey='building1' {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes['Box001_Material_#25_0'].geometry}
                material={materials.Material_25}
                position={[3.652, 0, 5.608]}
                rotation={[-Math.PI / 2, 0, 0]}
            />
        </e.group>
    )
}

useGLTF.preload('/building_3.glb')
