/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 grove_street.glb 
Author: Donstereo (https://sketchfab.com/Donstereo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/grand-theft-auto-san-andreas-grove-street-4dbdbe00c5cf46d8a2ef220045f58d9b
Title: Grand theft auto San Andreas | Grove street
*/

//disable eslint and typescript for this file
/* eslint-disable */
// @ts-nocheck

import { useGLTF } from '@react-three/drei'
// import { editable as e } from '@theatre/r3f'

export default function GroveStreet(props) {
  const { nodes, materials } = useGLTF('/grove_street.glb')
  return (
    <group theatreKey='grove_street' {...props} dispose={null}>
      <group position={[27.994, 5.807, -1.12]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.color} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.color} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.color} />
      </group>
    </group>
  )
}

useGLTF.preload('/grove_street.glb')
