/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 vice_city_map.glb 
Author: dark_igorek (https://sketchfab.com/dark_igorek)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gta-vice-city-ea315a9a83c142278e5f825ba2ffe0fb
Title: GTA Vice City
*/

//disable eslint and typescript for this file
/* eslint-disable */
// @ts-nocheck

import { useGLTF } from '@react-three/drei'
// import { editable as e } from '@theatre/r3f'
import { RigidBody } from '@react-three/rapier'

export default function ViceCity(props) {
  const { nodes, materials } = useGLTF('/vice_city_map.glb')
  return (
    <RigidBody type='fixed' colliders='trimesh' scale={[0.8, 0.8, 0.8]} rotation={[0, 0, 0]}>
      <group {...props} scale={[0.8, 0.8, 0.8]} rotation={[0, 0, 0]} dispose={null}>
        <group position={[14.75, -0.229, 2.557]}>
          <mesh geometry={nodes.Object_6.geometry} material={materials.building} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.material_0} />
        </group>
        <mesh geometry={nodes.Object_4.geometry} material={materials.building} position={[14.75, -0.229, 2.557]} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.hotel_details} position={[21.075, 24.624, 10.063]} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.hotel_details} position={[21.075, 24.624, -5.153]} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.hotel_details} position={[21.075, 17.994, 16.14]} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.hotel_details} position={[21.075, 17.994, -10.916]} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.hotel_details} position={[23.025, 19.853, 2.557]} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.hotel_details} position={[23.025, 11.975, 2.557]} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.hotel_details} position={[23.025, 8.149, 2.557]} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.hotel_details} position={[23.025, 15.803, 2.557]} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.hotel_details} position={[14.75, -0.229, -12.7]} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.hotel_details} position={[14.75, -0.229, 2.557]} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.enviroument} position={[25.487, -0.452, -9.536]} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.enviroument} position={[25.487, -0.452, -14.415]} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.enviroument} position={[25.487, -0.452, 12.584]} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.enviroument} position={[25.487, -0.452, 17.326]} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.hotel_details} position={[22.12, 27.347, 2.553]} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.enviroument} position={[13.369, -2.384, -29.047]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_41.geometry} material={materials.enviroument} position={[13.369, -2.384, -29.047]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Object_43.geometry} material={materials.cheetah} position={[41.857, -0.064, 17.006]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.Object_45.geometry} material={materials.hotel_details} position={[9.984, 19.472, -11.754]} />
        <mesh geometry={nodes.Object_47.geometry} material={materials.hotel_details} position={[10.222, 19.505, -12.05]} />
        <mesh geometry={nodes.Object_49.geometry} material={materials.hotel_details} position={[15.234, 19.472, -11.754]} />
        <mesh geometry={nodes.Object_51.geometry} material={materials.hotel_details} position={[15.472, 19.505, -12.05]} />
        <mesh geometry={nodes.Object_53.geometry} material={materials.hotel_details} position={[9.984, 19.472, -9.496]} />
        <mesh geometry={nodes.Object_55.geometry} material={materials.hotel_details} position={[10.222, 19.505, -9.792]} />
        <mesh geometry={nodes.Object_57.geometry} material={materials.hotel_details} position={[15.234, 19.472, -9.496]} />
        <mesh geometry={nodes.Object_59.geometry} material={materials.hotel_details} position={[15.472, 19.505, -9.792]} />
        <mesh geometry={nodes.Object_61.geometry} material={materials.hotel_details} position={[9.984, 5.942, -15.285]} />
        <mesh geometry={nodes.Object_63.geometry} material={materials.hotel_details} position={[10.222, 5.975, -15.58]} />
        <mesh geometry={nodes.Object_65.geometry} material={materials.hotel_details} position={[10.285, 4.375, -14.69]} />
        <mesh geometry={nodes.Object_67.geometry} material={materials.hotel_details} position={[15.234, 5.942, -15.285]} />
        <mesh geometry={nodes.Object_69.geometry} material={materials.hotel_details} position={[15.472, 5.975, -15.58]} />
        <mesh geometry={nodes.Object_71.geometry} material={materials.hotel_details} position={[15.535, 4.375, -14.69]} />
        <mesh geometry={nodes.Object_73.geometry} material={materials.hotel_details} position={[2.519, 13.774, 6.909]} />
        <mesh geometry={nodes.Object_75.geometry} material={materials.hotel_details} position={[2.224, 13.806, 6.671]} />
        <mesh geometry={nodes.Object_77.geometry} material={materials.hotel_details} position={[3.114, 12.207, 6.609]} />
        <mesh geometry={nodes.Object_79.geometry} material={materials.hotel_details} position={[2.519, 13.774, -4.679]} />
        <mesh geometry={nodes.Object_81.geometry} material={materials.hotel_details} position={[2.224, 13.806, -4.917]} />
        <mesh geometry={nodes.Object_83.geometry} material={materials.hotel_details} position={[3.114, 12.207, -4.979]} />
        <mesh geometry={nodes.Object_85.geometry} material={materials.hotel_details} position={[15.535, 5.942, 20.312]} />
        <mesh geometry={nodes.Object_87.geometry} material={materials.hotel_details} position={[15.297, 5.975, 20.607]} />
        <mesh geometry={nodes.Object_89.geometry} material={materials.hotel_details} position={[15.234, 4.375, 19.717]} />
        <mesh geometry={nodes.Object_91.geometry} material={materials.hotel_details} position={[10.285, 5.942, 20.312]} />
        <mesh geometry={nodes.Object_93.geometry} material={materials.hotel_details} position={[10.047, 5.975, 20.607]} />
        <mesh geometry={nodes.Object_95.geometry} material={materials.hotel_details} position={[9.984, 4.375, 19.717]} />
        <mesh geometry={nodes.Object_97.geometry} material={materials.enviroument} position={[25.478, -0.547, -10.887]} />
        <mesh geometry={nodes.Object_99.geometry} material={materials.enviroument} position={[25.419, -0.547, 16.106]} />
        <mesh geometry={nodes.Object_101.geometry} material={materials.cheetah} position={[41.857, -0.064, 17.006]} rotation={[Math.PI / 2, 0, Math.PI]} />
        <mesh geometry={nodes.Object_103.geometry} material={materials.cheetah} position={[41.857, -0.064, 17.006]} rotation={[Math.PI / 2, 0, Math.PI]} />
        <mesh geometry={nodes.Object_105.geometry} material={materials.hotel_details} position={[22.134, 0.692, -4.789]} />
        <mesh geometry={nodes.Object_107.geometry} material={materials.hotel_details} position={[22.134, 0.692, -10.99]} />
        <mesh geometry={nodes.Object_109.geometry} material={materials.hotel_details} position={[22.134, 0.692, 9.9]} />
        <mesh geometry={nodes.Object_111.geometry} material={materials.hotel_details} position={[22.134, 0.692, 16.229]} />
        <mesh geometry={nodes.Object_113.geometry} material={materials.cheetah} position={[41.857, -0.533, 16.758]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.Object_115.geometry} material={materials.cheetah} position={[41.857, -0.104, 17.006]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.Object_117.geometry} material={materials.enviroument} position={[5.737, -0.104, -19.822]} rotation={[0, Math.PI / 2, 0]} />
        <mesh geometry={nodes.Object_119.geometry} material={materials.enviroument} position={[46.527, -0.11, 22.374]} rotation={[-Math.PI, 0, -Math.PI]} />
        <mesh geometry={nodes.Object_121.geometry} material={materials.enviroument} position={[-8.136, -0.939, -11.647]} rotation={[-0.95, 1.097, -0.603]} />
        <mesh geometry={nodes.Object_123.geometry} material={materials.enviroument} position={[-0.71, -1.126, -4.959]} rotation={[-0.95, 1.097, -0.603]} />
        <mesh geometry={nodes.Object_125.geometry} material={materials.hotel_details} position={[24.708, 6.443, 8.531]} />
        <mesh geometry={nodes.Object_127.geometry} material={materials.hotel_details} position={[24.708, 6.443, 8.489]} />
        <mesh geometry={nodes.Object_129.geometry} material={materials.hotel_details} position={[24.708, 6.443, 7.024]} />
        <mesh geometry={nodes.Object_131.geometry} material={materials.hotel_details} position={[24.708, 6.443, 5.594]} />
        <mesh geometry={nodes.Object_133.geometry} material={materials.hotel_details} position={[24.708, 6.443, -1.766]} />
        <mesh geometry={nodes.Object_135.geometry} material={materials.hotel_details} position={[24.708, 6.443, 3.963]} />
        <mesh geometry={nodes.Object_137.geometry} material={materials.hotel_details} position={[24.708, 6.443, 2.556]} />
        <mesh geometry={nodes.Object_139.geometry} material={materials.hotel_details} position={[24.708, 6.443, 0.524]} />
        <mesh geometry={nodes.Object_141.geometry} material={materials.hotel_details} position={[24.708, 6.443, -0.954]} />
        <mesh geometry={nodes.Object_143.geometry} material={materials.hotel_details} position={[24.708, 6.443, -3.345]} />
        <mesh geometry={nodes.Object_145.geometry} material={materials.hotel_details} position={[24.708, 6.443, -4.014]} />
        <mesh geometry={nodes.Object_147.geometry} material={materials.enviroument} position={[47.582, -0.94, -20.23]} />
        <mesh geometry={nodes.Object_149.geometry} material={materials.enviroument} position={[27.108, -0.94, 24.766]} />
        <mesh geometry={nodes.Object_151.geometry} material={materials.enviroument} position={[47.582, -0.94, 7.956]} />
        <mesh geometry={nodes.Object_153.geometry} material={materials.hotel_details} position={[14.75, -0.229, 2.557]} />
        <mesh geometry={nodes.Object_155.geometry} material={materials.hotel_details} position={[14.75, -0.229, 2.557]} />
        <mesh geometry={nodes.Object_157.geometry} material={materials.hotel_details} position={[14.75, -0.229, 2.557]} />
        <mesh geometry={nodes.Object_159.geometry} material={materials.hotel_details} position={[14.75, -0.229, 2.557]} />
        <mesh geometry={nodes.Object_161.geometry} material={materials.hotel_details} position={[14.75, -0.229, 2.557]} />
        <mesh geometry={nodes.Object_163.geometry} material={materials.hotel_details} position={[14.75, -0.229, 2.557]} />
        <mesh geometry={nodes.Object_165.geometry} material={materials.hotel_details} position={[14.75, 3.765, 2.557]} />
        <mesh geometry={nodes.Object_167.geometry} material={materials.hotel_details} position={[14.75, -0.229, -12.7]} />
        <mesh geometry={nodes.Object_169.geometry} material={materials.hotel_details} position={[14.75, -0.229, -12.7]} />
        <mesh geometry={nodes.Object_171.geometry} material={materials.hotel_details} position={[14.75, -0.229, -12.7]} />
        <mesh geometry={nodes.Object_173.geometry} material={materials.hotel_details} position={[14.75, 3.765, -12.7]} />
        <mesh geometry={nodes.Object_175.geometry} material={materials.hotel_details} position={[14.75, -0.229, -24.31]} />
        <mesh geometry={nodes.Object_177.geometry} material={materials.hotel_details} position={[14.75, -0.229, -18.505]} />
        <mesh geometry={nodes.Object_179.geometry} material={materials.hotel_details} position={[21.075, 6.633, 10.063]} />
        <mesh geometry={nodes.Object_181.geometry} material={materials.hotel_details} position={[21.075, 6.633, -5.153]} />
        <mesh geometry={nodes.Object_183.geometry} material={materials.enviroument} position={[25.878, 0.104, -5.68]} />
        <mesh geometry={nodes.Object_185.geometry} material={materials.enviroument} position={[25.878, 0.104, 10.696]} rotation={[-Math.PI, -0.314, -Math.PI]} />
        <mesh geometry={nodes.Object_187.geometry} material={materials.hotel_details} position={[24.335, 6.32, -4.712]} />
        <mesh geometry={nodes.Object_189.geometry} material={materials.hotel_details} position={[24.335, 6.523, -4.712]} />
        <mesh geometry={nodes.Object_191.geometry} material={materials.hotel_details} position={[24.335, 6.32, 18.515]} />
        <mesh geometry={nodes.Object_193.geometry} material={materials.hotel_details} position={[24.335, 6.523, 18.515]} />
        <mesh geometry={nodes.Object_195.geometry} material={materials.hotel_details} position={[21.075, 14.298, 16.14]} />
        <mesh geometry={nodes.Object_197.geometry} material={materials.hotel_details} position={[21.075, 10.465, 16.14]} />
        <mesh geometry={nodes.Object_199.geometry} material={materials.hotel_details} position={[21.075, 6.633, 16.14]} />
        <mesh geometry={nodes.Object_201.geometry} material={materials.hotel_details} position={[21.075, 14.298, -10.916]} />
        <mesh geometry={nodes.Object_203.geometry} material={materials.hotel_details} position={[21.075, 10.465, -10.916]} />
        <mesh geometry={nodes.Object_205.geometry} material={materials.hotel_details} position={[21.075, 6.633, -10.916]} />
        <mesh geometry={nodes.Object_207.geometry} material={materials.hotel_details} position={[21.075, 14.298, 10.063]} />
        <mesh geometry={nodes.Object_209.geometry} material={materials.hotel_details} position={[21.075, 10.465, 10.063]} />
        <mesh geometry={nodes.Object_211.geometry} material={materials.hotel_details} position={[21.075, 18.321, 10.063]} />
        <mesh geometry={nodes.Object_213.geometry} material={materials.hotel_details} position={[21.075, 14.298, -5.153]} />
        <mesh geometry={nodes.Object_215.geometry} material={materials.hotel_details} position={[21.075, 10.465, -5.153]} />
        <mesh geometry={nodes.Object_217.geometry} material={materials.hotel_details} position={[21.075, 18.321, -5.153]} />
        <mesh geometry={nodes.Object_219.geometry} material={materials.car_oceanic} position={[31.957, -0.224, -4.039]} />
        <mesh geometry={nodes.Object_221.geometry} material={materials.car_oceanic} position={[31.977, -0.309, -4.063]} />
        <mesh geometry={nodes.Object_223.geometry} material={materials.car_oceanic} position={[31.957, -0.23, -4.039]} />
        <mesh geometry={nodes.Object_225.geometry} material={materials.car_oceanic} position={[31.957, -0.224, -4.039]} rotation={[0, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.Object_227.geometry} material={materials.car_oceanic} position={[31.957, -0.224, -4.039]} />
        <mesh geometry={nodes.Object_229.geometry} material={materials.car_oceanic} position={[31.957, -0.224, -4.039]} />
        <mesh geometry={nodes.Object_231.geometry} material={materials.hotel_details} position={[2.014, 5.329, 10.662]} />
        <mesh geometry={nodes.Object_233.geometry} material={materials.hotel_details} position={[6.355, 1.438, 9.389]} />
        <mesh geometry={nodes.Object_235.geometry} material={materials.hotel_details} position={[14.75, -0.229, 2.557]} />
        <mesh geometry={nodes.Object_237.geometry} material={materials.hotel_details} position={[10.179, -0.456, -14.526]} />
        <mesh geometry={nodes.Object_239.geometry} material={materials.hotel_details} position={[20.303, 26.129, 11.785]} />
        <mesh geometry={nodes.Object_241.geometry} material={materials.hotel_details} position={[19.566, 26.666, 11.785]} />
        <mesh geometry={nodes.Object_243.geometry} material={materials.hotel_details} position={[16.704, 26.666, 11.785]} />
        <mesh geometry={nodes.Object_245.geometry} material={materials.hotel_details} position={[13.856, 26.666, 11.785]} />
        <mesh geometry={nodes.Object_247.geometry} material={materials.hotel_details} position={[11.004, 26.666, 11.785]} />
        <mesh geometry={nodes.Object_249.geometry} material={materials.hotel_details} position={[20.303, 26.129, -6.819]} />
        <mesh geometry={nodes.Object_251.geometry} material={materials.hotel_details} position={[19.566, 26.666, -6.819]} />
        <mesh geometry={nodes.Object_253.geometry} material={materials.hotel_details} position={[16.704, 26.666, -6.819]} />
        <mesh geometry={nodes.Object_255.geometry} material={materials.hotel_details} position={[13.856, 26.666, -6.819]} />
        <mesh geometry={nodes.Object_257.geometry} material={materials.hotel_details} position={[11.004, 26.666, -6.819]} />
        <mesh geometry={nodes.Object_259.geometry} material={materials.enviroument} position={[47.055, -2.091, -13.906]} />
        <mesh geometry={nodes.Object_261.geometry} material={materials.enviroument} position={[47.395, -1.416, 2.337]} rotation={[-Math.PI, 0.933, -Math.PI]} />
        <mesh geometry={nodes.Object_263.geometry} material={materials.enviroument} position={[47.395, -0.401, 14.413]} rotation={[-Math.PI, -0.223, -Math.PI]} />
        <mesh geometry={nodes.Object_265.geometry} material={materials.enviroument} position={[47.345, -1.468, -24.482]} rotation={[-Math.PI, 0.822, -Math.PI]} />
        <mesh geometry={nodes.Object_267.geometry} material={materials.enviroument} position={[47.395, -0.401, 14.413]} rotation={[-Math.PI, -0.223, -Math.PI]} />
        <mesh geometry={nodes.Object_269.geometry} material={materials.enviroument} position={[47.395, -1.416, 28.481]} rotation={[0, -1.369, 0]} />
        <mesh geometry={nodes.Object_271.geometry} material={materials.enviroument} position={[28.069, -1.416, -10.883]} rotation={[0, 1.537, 0]} />
        <mesh geometry={nodes.Object_273.geometry} material={materials.enviroument} position={[28.188, -1.416, 15.954]} rotation={[-Math.PI, 1.303, -Math.PI]} />
        <mesh geometry={nodes.Object_275.geometry} material={materials.enviroument} position={[47.318, -1.635, 28.601]} />
        <mesh geometry={nodes.Object_277.geometry} material={materials.enviroument} position={[47.318, -1.635, 14.308]} />
        <mesh geometry={nodes.Object_279.geometry} material={materials.enviroument} position={[47.318, -1.635, 2.143]} />
        <mesh geometry={nodes.Object_281.geometry} material={materials.enviroument} position={[47.318, -1.635, -13.776]} />
        <mesh geometry={nodes.Object_283.geometry} material={materials.enviroument} position={[47.318, -1.635, -24.607]} />
        <mesh geometry={nodes.Object_285.geometry} material={materials.enviroument} position={[28.171, -1.635, 15.736]} />
        <mesh geometry={nodes.Object_287.geometry} material={materials.enviroument} position={[28.171, -1.635, -11.054]} />
        <mesh geometry={nodes.Object_289.geometry} material={materials.enviroument} position={[2.871, -1.416, -19.132]} rotation={[0, 1.537, 0]} />
        <mesh geometry={nodes.Object_291.geometry} material={materials.enviroument} position={[2.973, -1.635, -19.302]} />
        <mesh geometry={nodes.Object_293.geometry} material={materials.enviroument} position={[-6.525, -0.873, -13.81]} />
        <mesh geometry={nodes.Object_295.geometry} material={materials.enviroument} position={[-1.652, -0.815, -17.768]} rotation={[0, -0.922, 0]} />
        <mesh geometry={nodes.Object_297.geometry} material={materials.enviroument} position={[-6.969, -2.25, 19.146]} />
        <mesh geometry={nodes.Object_299.geometry} material={materials.hotel_details} position={[10.941, 19.443, 13.552]} />
        <mesh geometry={nodes.Object_301.geometry} material={materials.hotel_details} position={[19.82, 19.594, 18.786]} />
        <mesh geometry={nodes.Object_303.geometry} material={materials.hotel_details} position={[19.82, 19.594, -13.679]} />
        <mesh geometry={nodes.Object_305.geometry} material={materials.hotel_details} position={[19.084, 20.131, -13.679]} />
        <mesh geometry={nodes.Object_307.geometry} material={materials.hotel_details} position={[16.217, 20.131, -13.679]} />
        <mesh geometry={nodes.Object_309.geometry} material={materials.hotel_details} position={[13.351, 20.131, -13.679]} />
        <mesh geometry={nodes.Object_311.geometry} material={materials.hotel_details} position={[10.491, 20.131, -13.679]} />
        <mesh geometry={nodes.Object_313.geometry} material={materials.hotel_details} position={[7.645, 20.131, -13.679]} />
        <mesh geometry={nodes.Object_315.geometry} material={materials.hotel_details} position={[3.958, 20.131, 16.31]} />
        <mesh geometry={nodes.Object_317.geometry} material={materials.hotel_details} position={[3.958, 20.131, 13.47]} />
        <mesh geometry={nodes.Object_319.geometry} material={materials.hotel_details} position={[3.958, 20.131, 10.629]} />
        <mesh geometry={nodes.Object_321.geometry} material={materials.hotel_details} position={[3.958, 20.131, 7.789]} />
        <mesh geometry={nodes.Object_323.geometry} material={materials.hotel_details} position={[3.958, 20.131, 4.949]} />
        <mesh geometry={nodes.Object_325.geometry} material={materials.hotel_details} position={[3.958, 19.594, 17.023]} />
        <mesh geometry={nodes.Object_327.geometry} material={materials.hotel_details} position={[19.084, 20.131, 18.786]} />
        <mesh geometry={nodes.Object_329.geometry} material={materials.hotel_details} position={[16.217, 20.131, 18.786]} />
        <mesh geometry={nodes.Object_331.geometry} material={materials.hotel_details} position={[13.351, 20.131, 18.786]} />
        <mesh geometry={nodes.Object_333.geometry} material={materials.hotel_details} position={[10.491, 20.131, 18.786]} />
        <mesh geometry={nodes.Object_335.geometry} material={materials.hotel_details} position={[7.645, 20.131, 18.786]} />
        <mesh geometry={nodes.Object_337.geometry} material={materials.hotel_details} position={[3.608, 19.594, -7.522]} />
        <mesh geometry={nodes.Object_339.geometry} material={materials.hotel_details} position={[3.608, 19.594, -12.202]} />
        <mesh geometry={nodes.Object_341.geometry} material={materials.hotel_details} position={[1.88, 7.211, -10.962]} />
        <mesh geometry={nodes.Object_343.geometry} material={materials.hotel_details} position={[1.88, 1.088, -8.753]} />
        <mesh geometry={nodes.Object_345.geometry} material={materials.hotel_details} position={[1.614, 7.971, -7.515]} />
        <mesh geometry={nodes.Object_347.geometry} material={materials.hotel_details} position={[1.614, 14.07, -7.515]} />
        <mesh geometry={nodes.Object_349.geometry} material={materials.hotel_details} position={[1.924, 18.79, -9.821]} />
        <mesh geometry={nodes.Object_351.geometry} material={materials.hotel_details} position={[1.614, 19.967, -7.515]} />
        <mesh geometry={nodes.Object_353.geometry} material={materials.hotel_details} position={[1.924, 12.992, -9.821]} rotation={[Math.PI, 0, 0]} />
        <mesh geometry={nodes.Object_355.geometry} material={materials.hotel_details} position={[1.924, 6.943, -9.821]} />
        <mesh geometry={nodes.Object_357.geometry} material={materials.hotel_details} position={[2.782, 13.414, -8.848]} />
        <mesh geometry={nodes.Object_359.geometry} material={materials.terrain} position={[30.386, -0.896, 22.786]} />
        <mesh geometry={nodes.Object_361.geometry} material={materials.terrain} position={[30.386, -0.853, 22.786]} />
        <mesh geometry={nodes.Object_363.geometry} material={materials.enviroument} position={[2.902, 3.434, -11.605]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Object_365.geometry} material={materials.enviroument} position={[2.889, 2.394, -12.874]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Object_367.geometry} material={materials.enviroument} position={[4.584, 3.434, 5.71]} rotation={[0, 0, Math.PI / 2]} />
        <mesh geometry={nodes.Object_369.geometry} material={materials.enviroument} position={[2.763, 0.851, -3.105]} />
        <mesh geometry={nodes.Object_371.geometry} material={materials.enviroument} position={[3.548, 1.077, 3.631]} />
        <mesh geometry={nodes.Object_373.geometry} material={materials.enviroument} position={[3.168, 1.077, 1.991]} rotation={[0, -0.232, 0]} />
        <mesh geometry={nodes.Object_375.geometry} material={materials.enviroument} position={[3.48, 2.129, 2.601]} />
        <mesh geometry={nodes.Object_377.geometry} material={materials.enviroument} position={[-0.881, -1.51, 17.14]} />
        <mesh geometry={nodes.Object_379.geometry} material={materials.hotel_details} position={[17.122, 25.586, -1.632]} />
        <mesh geometry={nodes.Object_381.geometry} material={materials.hotel_details} position={[12.318, 25.586, -1.632]} />
        <mesh geometry={nodes.Object_383.geometry} material={materials.hotel_details} position={[15.378, 25.721, 8.391]} />
        <mesh geometry={nodes.Object_385.geometry} material={materials.hotel_details} position={[16.757, 30.922, 8.391]} />
        <mesh geometry={nodes.Object_387.geometry} material={materials.hotel_details} position={[6.728, 20.112, 9.101]} />
        <mesh geometry={nodes.Object_389.geometry} material={materials.cheetah} position={[41.857, -0.064, 17.006]} rotation={[Math.PI, 0, Math.PI / 2]} />
      </group>
    </RigidBody>
  )
}

useGLTF.preload('/vice_city_map.glb')
