/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

//disable eslint and typescript for this file
/* eslint-disable */
// @ts-nocheck

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'
import * as THREE from 'three'

const invisibleMaterial = new THREE.MeshBasicMaterial({ visible: false })

export default function Model(props) {
    const { nodes, materials } = useGLTF('/vice_city_mesh.glb')
    return (
        <RigidBody type='fixed' colliders='trimesh' scale={[0.6, 0.6, 0.6]} rotation={[0, 0, 0]}>
            <group {...props} rotation={[0, 0, 0]} dispose={null} >
                <mesh
                    geometry={nodes.Cube.geometry}
                    material={invisibleMaterial}
                    position={[8.377, 7.679, 2.536]}
                />
                <mesh
                    geometry={nodes.Cube001.geometry}
                    material={invisibleMaterial}
                    position={[47.323, 2.238, 2.103]}
                />
                <mesh
                    geometry={nodes.Cube002.geometry}
                    material={invisibleMaterial}
                    position={[47.323, 2.238, -13.881]}
                />
                <mesh
                    geometry={nodes.Cube003.geometry}
                    material={invisibleMaterial}
                    position={[47.323, 2.238, -24.551]}
                />
                <mesh
                    geometry={nodes.Cube004.geometry}
                    material={invisibleMaterial}
                    position={[47.323, 2.238, 14.36]}
                />
                <mesh
                    geometry={nodes.Cube005.geometry}
                    material={invisibleMaterial}
                    position={[47.323, 2.238, 28.597]}
                />
                <mesh
                    geometry={nodes.Cube006.geometry}
                    material={invisibleMaterial}
                    position={[28.185, 2.314, -11.065]}
                />
                <mesh
                    geometry={nodes.Cube007.geometry}
                    material={invisibleMaterial}
                    position={[28.185, 2.314, 15.69]}
                />
                <mesh
                    geometry={nodes.Cube008.geometry}
                    material={invisibleMaterial}
                    position={[2.978, 2.347, -19.356]}
                />
                <mesh
                    geometry={nodes.Cube009.geometry}
                    material={invisibleMaterial}
                    position={[5.744, 0.009, -19.493]}
                />
                <mesh
                    geometry={nodes.Cube010.geometry}
                    material={invisibleMaterial}
                    position={[46.928, 0.009, 22.386]}
                />
                <mesh
                    geometry={nodes.Cube011.geometry}
                    material={invisibleMaterial}
                    position={[47.618, 3.57, 8.001]}
                />
                <mesh
                    geometry={nodes.Cube012.geometry}
                    material={invisibleMaterial}
                    position={[47.576, 3.57, -20.274]}
                />
                <mesh
                    geometry={nodes.Cube013.geometry}
                    material={invisibleMaterial}
                    position={[27.082, 3.57, 24.761]}
                />
                <mesh
                    geometry={nodes.Cube014.geometry}
                    material={invisibleMaterial}
                    position={[31.977, -0.493, -3.893]}
                />
                <mesh
                    geometry={nodes.Cube015.geometry}
                    material={invisibleMaterial}
                    position={[31.977, 0.681, -3.893]}
                />
                <mesh
                    geometry={nodes.Cube016.geometry}
                    material={invisibleMaterial}
                    position={[41.88, -0.368, 16.778]}
                />
                <mesh
                    geometry={nodes.Cube017.geometry}
                    material={invisibleMaterial}
                    position={[10.042, -1.089, 2.639]}
                />
                <mesh
                    geometry={nodes.Cube018.geometry}
                    material={invisibleMaterial}
                    position={[49.096, -1.132, 2.639]}
                />
                <mesh
                    geometry={nodes.Cube019.geometry}
                    material={invisibleMaterial}
                    position={[21.506, -2.367, 2.801]}
                />
                <mesh
                    geometry={nodes.Cube019.geometry}
                    material={invisibleMaterial} // Add invisible material here
                    position={[21.506, -2.367, 2.801]}
                />
            </group>
        </RigidBody>
    )
}

useGLTF.preload('/vice_city_mesh.glb')


